// 1: Delete a node from BST: https://www.geeksforgeeks.org/problem...
// 2: Search a node in BST: https://www.geeksforgeeks.org/problem...
// 3: Insert a node in a BST: https://www.geeksforgeeks.org/problem...