// 1: Merge two binary Max heaps: https://www.geeksforgeeks.org/problem...
// 2: Is Binary Tree Heap: https://www.geeksforgeeks.org/problem...
// 3: BST to max heap: https://www.geeksforgeeks.org/problem...
