// 1: Kth smallest element: https://www.geeksforgeeks.org/problem...
// 2: Kth Largest Element in an Array: https://leetcode.com/problems/kth-lar...
// 3: Kth largest element in a stream: https://www.geeksforgeeks.org/problem...
// 4: Sum of elements between k1'th and k2'th smallest elements: https://www.geeksforgeeks.org/problem...