

// 1: Height of Heap : https://www.geeksforgeeks.org/problem...
// 2:Minimum Cost of ropes : https://www.geeksforgeeks.org/problem...[]=0&category[]=Heap&sortBy=submissions
// 3:Magician and Chocolates: https://www.interviewbit.com/problems...
// 4: Last Stone Weight: https://leetcode.com/problems/last-st...
// 5: Take Gifts From the Richest Pile: https://leetcode.com/problems/take-gi...
// 6: Profit Maximisation: https://www.interviewbit.com/problems...
